mobify/astro-scaffold

package.json
Just updating Astro to 0.7.1 (removes grunt-harp dependency).
=> Update Astro to 0.7.1

app/tests/system/pageObjects/androidAction.js, app/tests/system/pageObjects/androidActions.js
Abstract System Level Actions for Android into a Action Library
JIRA: 
https://mobify.atlassian.net/browse/CSOG-5 
Added androidAction.js file under pageObjects folder, including:
- Generalize the native xpath selectors
- Generalize native action functions
- Navigate using the hamburger menu
- Use the system level back button
- Generalize setting the windowhandler object
- Update the Appium to the latest version
- Clone https://github.com/mobify/generator-astro
- Change `generator.sh`:
```
SCAFFOLD_VERSION="CSOG-5_system_action_android"
SCAFFOLD_URL="https://github.com/mobify/astro-scaffold/archive/CSOG-5_system_action_android.zip"
```
- Run `./generator.sh`
- `cd` into generated project and run `./scripts/ios-appium.sh`
=> Abstract System Level Actions for Android into a Action Library

README.md
Added documentation for how to avoid a slow first-time build experience
JIRA: **https://mobify.atlassian.net/browse/HYB-669**
- Added documentation for how to avoid a slow first-time build experience
- `git clone` the astro-scaffold (or generate a new project)
- `git clean -fdx` (if you already had the scaffold cloned)
- Go through the updated docs, `npm install`-ing for astro-sdk as well
- Build the app in Xcode, observe it isn't brutally slow the first time
=> HYB-669: Update the docs to tell the developer that the first build will take quite a while

CHANGELOG.md, app/app.js, app/build-js.sh, app/scaffold-controllers/navigationController.js, app/scaffold-www/astro-client.js
Update back behaviour with new back event
JIRA: https://mobify.atlassian.net/browse/HYB-682
Linked PRs: https://github.com/mobify/astro/pull/420
- Listen on `backButtonPressed` instead of `onKeyDown`
- Close app if NavigationPlugin can't go back
- I had trouble running the build-js.sh...it couldn't find `../../app/scaffold-www/` when I pointed to a local verison of astro. Changed the copy command so that it worked on my setup.
- npm link to newest version of Astro develop
- Navigate forward in one of the sections.
- Use the hardware back button to go back through the navigation and then close the app when there are no more back navigations available
=> Updating back behaviour

CHANGELOG.md, ios/scaffold/AppDelegate.swift, scripts/ios-appium.sh
JIRA: **https://mobify.atlassian.net/browse/HYB-722**
- add a flag to the appium xcodebuild script to hook onto in AppDelegate and use UIWebView for tests
- run the scaffold and make sure we are using WKWebView for iOS 9+
- run the appium tests and make sure they pass (meaning they are using UIWebView)
=> Use UIWebView for appium tests until appium supports WKWebView

CHANGELOG.md, app/scaffold-controllers/navigationController.js
Updating navigation handler to work with new navigation method.
JIRA: https://mobify.atlassian.net/browse/HYB-726
Linked PRs: 
- pass in the navigation handler method to the navigateToUrl method
- Click link to navigate in app
- Header should still have the cart icon
=> Fix header icons during navigation

android/.idea/modules.xml, android/scaffold/build.gradle, android/scaffold/scaffold.iml
Fix Android build variants and remove the reference to the pre-NPM Astro project reference
- Remove pre-NPM Astro project reference
- Update build.gradle to synchronize debug/release
- Add Android debug test coverage so debug builds can run on device
- Change the variant to debug or release, run the app
~~- [ ] Change works in both Android and iOS.~~
~~- [ ] CHANGELOG.md has been updated.~~
~~- [ ] Both tab layout and drawer layout are fully functional in ios. (Set `iosUsingTabLayout` in `baseConfig`)~~
Update build.gradle so build variants are in sync
=> Fix Android build variants

README.md
Fixes the bash snippet that generates the `user-env.sh` file. The `/d` command must be the last piece of the `sed` command as it specifies to delete to the end of the line.
JIRA: N/A
Linked PRs: N/A
- Remove closing quote in the `sed` command (not needed and breaks the command)
- Run the generator
- `cd` into the newly generated project dir
- Run the bash snippet. You should see a new `app/user-env.sh` file with the path to your `npm` install
~- [ ] Change works in both Android and iOS.~
-~ [ ] CHANGELOG.md has been updated.~
~- [ ] Scaffold is working. If a new feature was added, it was added to the Scaffold app.~
~- [ ] Both tab layout and drawer layout are fully functional in ios. (Set `iosUsingTabLayout` in `baseConfig`)~
=> Fix `user-env.sh` generation snippet

CHANGELOG.md, app/build-js.sh, buddybuild_postclone.sh, package.json
JIRA: **https://mobify.atlassian.net/browse/HYB-788**
- add buddybuild_postclone.sh script
- update package.json to install grunt-cli and update scripts to use it instead of a globally-installed one
- Generate a project based on this branch
- Run the buddybuild script
- Build and test on both platforms
~~- [ ] Both tab layout and drawer layout are fully functional in ios. (Set `iosUsingTabLayout` in `baseConfig`)~~
=> HYB-788: As an Astro Developer, I want the scaffold to work on buildbuddy out of the box

app/app-controllers/tabBarController.js
[HYB-805] iOS: Switching tabs programmatically should highlight selected tab
JIRA: **[[HYB-805] iOS: Switching tabs programmatically should highlight selected tab](https://mobify.atlassian.net/browse/HYB-805)**
Linked PRs: **None**
- Pulling in [fix from eXtra](https://github.com/mobify/extra-mobile/blob/61f0ddd69586376b99d2431ff29c7e17671f80d9/native/app/extra-controllers/tabBarController.js#L103) to highlight selected tab when programmatically switching tabs
You can view the same changes in eXtra by following the steps:
1. Run eXtra's `develop` branch on iOS
1. Go to a PDP and add item to cart
1. Switch to a different tab
1. Open cart & tap on a product in the cart to initiate tab switch & navigation
1. Observe the first tab should be highlighted.
Or temporarily make tabBarController …
=> [HYB-805] iOS: Switching tabs programmatically should highlight selected tab

CHANGELOG.md, android/.idea/gradle.xml, android/.idea/misc.xml, android/.idea/modules.xml, android/scaffold/scaffold.iml, android/settings.gradle, package.json
The Android `pushclient` module must be included in `settings.gradle` file of the app in order for the app to compile.
JIRA: https://mobify.atlassian.net/browse/MSG-355
Linked PRs: None
- Update `settings.gradle` to include `pushclient` module
- Point package.json at develop version of astro
- Build the project in Android and install the app
=> MSG-355: Include Android pushclient in app

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, app/app-controllers/navigationController.js, app/app-controllers/tabBarController.js, ios/scaffold/Info.plist
JIRA: **https://mobify.atlassian.net/browse/HYB-786 https://mobify.atlassian.net/browse/HYB-803**
- Set iOS app to be portrait-only (this was already true on Android)
- Implement pop-to-root support when you tap on the current tab in the tab bar controller (iOS only)
- Fix bug where selecting a tab calls the (formerly named) `selectTab` function twice (and therefore popped to root on every tab tap)
- Fixed PR template to remove "feature added to scaffold"...obviously if you are making a change to scaffold you are probably doing that and "Change works in both Android and iOS" covers that.
- iOS - run the app and rotate the phone
- iOS pop to root, make sure not every tap on a tab pops to root (only should happen if you are already on the tab)
- android - make sure that back/forward …
=> Portrait-only and pop to root support

CHANGELOG.md, ios/scaffold.xcodeproj/project.pbxproj, ios/scaffold.xcworkspace/contents.xcworkspacedata, package.json
Include the PushClient iOS library
~~JIRA: **(link to JIRA ticket)**~~
- Include the PushClient iOS library
- If https://github.com/mobify/astro/pull/512 has not been merged into astro develop yet, update your `package.json` to point to astro.git/#ios-push-integration
- Build the app for iOS
=> Include the PushClient iOS library

ios/Cordova/www/index.html
Allow emojis to be passed over the worker/native bridge by specifying `utf-8` charset in the iOS Cordova `index.html` file.
JIRA: **N/A**
Linked PRs: **N/A**
- Add `charset` `meta` tag with the `utf-8` value
- A good test is to try and pass an emoji from `app.js` to the `AlertViewPlugin`. The emoji should appear.
~~- [ ] CHANGELOG.md has been updated.~~
~~- [ ] Run the generator to make sure it still functions correctly.~~
~~- [ ] Both tab layout and drawer layout are fully functional in ios. (Set `iosUsingTabLayout` in `baseConfig`)~~
=> iOS Cordova Charset

.gitignore, CHANGELOG.md, app/tasks/config/eslint.js, app/tests/system/assertions/global.js, app/tests/system/pages/web/homepage.js, package.json, scripts/ios-appium.sh
The `package.json` dependencies are getting a bit stale. This PR updates them and fixes the linter config to point to the latest `mobify-code-style` rules.
**Note**: It seems like the Selenium tests are failing and probably have been for a while. I'm not addressing them in this PR but we should in a future PR... soon... 
JIRA: N/A
Linked PRs: N/A
- Upgrade to `grunt-eslint` v 19.0.0
- Fix eslint config for new version of eslint
- Fix new linter errors in `js` tests
- Run `npm i`
- Run `app/build-js.sh`
- Run the app on iOS and Android
=> Linter and`package.json` updates

CHANGELOG.md, app/build-js.sh, ios/scaffold.xcodeproj/project.pbxproj
Make `build-js.sh` smarter about finding `npm` when it's not in the path.
JIRA: N/A
Linked PRs: N/A
- The build script now checks if `~/.nvm` exists and if it does, assumes that that's where it can find npm.
- Start a new shell
- Remove nvm from the `$PATH`
- Run `build-js.sh` and make sure it prints out that it found `.nvm` and is sourcing it... then the build should succeed.
=> Make build-js.sh smarter about finding npm

.gitignore, app/app-www/html/error.html, app/app-www/html/left-drawer.html, app/app-www/html/search-bar.html, app/app-www/html/welcome.html, app/app-www/js/config.js, app/build-js.sh
Last PR?! 🎉 💥 
JIRA: **None**
Linked PRs: **None**
- Move third party dependencies into a `/build` folder, this makes it easier to manage our gitignore :)
- Make sure everything still works
- ~~[ ] CHANGELOG.md has been updated.~~
=> Move www dependencies

README.md, ios/scaffold/apple-app-site-association
Add the `apple-app-site-association` and update readme with instructions for setting up universal deep linking on customers site.
JIRA: https://mobify.atlassian.net/browse/HYB-695
Linked PRs: Deep linking mostly implemented in https://github.com/mobify/astro-scaffold/pull/106
- Add a site association file
- Inspection only
=> HYB-695: Add iOS site association file

CHANGELOG.md, ios/scaffold.xcodeproj/project.pbxproj, ios/scaffold/Info.plist
Set iOS project to 'iPhone' instead of 'Universal' - the majority of our builds do not include iPad support
~~JIRA: **(link to JIRA ticket)**~~
- Set iOS project to 'iPhone' instead of 'Universal'
- Build and run
~~- [ ] Change works in both Android and iOS.~~
~~- [ ] Both tab layout and drawer layout are fully functional in ios. (Set `useTabLayout` in `baseConfig`)~~
=> Set iOS project to 'iPhone' instead of 'Universal'

CHANGELOG.md, app/app-controllers/cart/cartModalController.js, app/app-controllers/error-screen/errorController.js, app/app-controllers/tabBarController.js, app/app-www/js/config.js, app/app.js, package.json
JIRA: **none**
Linked PRs: **https://github.com/mobify/astro/pull/621**
- Supply `canGoBack` function to `errorController` within the cart modal.
- Fix hardware back button functionality for modals (changes as a result of linked PR)
- Wire up hardware back button for tab layout
- fix: error dialog text -- wasn't getting filled in before due to dependency issue
- fix: error dialog back button should not show if app cannot go back
- Run scaffold
- Open cart
- Turn off internet on device
- Click a link in the cart (one of the items in the right drawer within the cart works)
- Ensure you get an error modal (previously there was none)
- Do this in multiple different scenarios and make sure back button + hardware back button work correctly (i.e. modals, tab vs. side-nav layout)
=> Fix errorController when displayed from cart and refactor hardware back button handling

app/build-js.sh, ios/Cordova/www/index.html, scripts/build-dependencies.sh
JIRA: **none**
Linked PRs: **none**
- copy `bluebird` over into `app-www` in `build-dependencies.sh`
- remove old directory check/create code in `build-js.sh` since it has been moved to `build-dependencies.sh` and building `app.js` shouldn't require that folder to exist
- Set the title in the cordova `index.html` to "Astro Worker" for easier debugging
- blow away your `app/app-www/js/build` directory
- `npm run deps`
- run scaffold app
- attach the safari debugger
=> Pull in build improvements resulting from eXtra Xcode 8 upgrade

ios/scaffold/AppDelegate.swift
Fixes a bug where the headerbar and navigationplugin become "unsynced" on launch. See linked Astro PR.
JIRA: https://mobify.atlassian.net/browse/HYB-936
Linked PRs: https://github.com/mobify/astro/pull/663
- Remove "run loop" spin in AppDelegate.
- Run the app
- Navigate forward and back
- Verify that the head bar remains in sync at all times.
~~- [ ] Change works in both Android and iOS.~~
~~- [ ] CHANGELOG.md has been updated.~~
=> Remove runloop spin, Astro fixed this finally!

CHANGELOG.md, android/scaffold/build.gradle, app/app-config/baseConfig.js, app/app.js, ios/scaffold.xcodeproj/project.pbxproj, package.json
Astro now supports multiple build configurations. Scaffold will support the same build configurations. 
JIRA: https://mobify.atlassian.net/browse/HYB-968
Linked PRs: https://github.com/mobify/astro/pull/714
https://github.com/mobify/generator-astro/pull/42
- Update with new build configurations for ios and android
- `App.js` checks the `ASTRO_PREVIEW` flag before it decides whether it needs to create and query the `PreviewController`
- Run different configurations of app (ios and android)
- When preview is disabled ensure that shake doesn't do anything
- When preview is enabled ensure that shaking causes the preview alert dialog to come up
- Check restarting the app shows the preview modal when preview is enabled in the alert dialog
=> [HYB-968]: Multiple build configurations to support builds with preview enabled

android/scaffold/build.gradle
Android build is broken post 0.17.6 release and webpack update. Fix the issue.
JIRA: None
Linked PRs: None
- Use build type instead of variant name to call buildJS tasks.
- Build and run android app
=> Broken android build with 4 variants and webpack changes

app/app.js, webpack.app.config.js
This PR fixes a bug where the welcome modal would appear twice, one on top of each other. I also remove the waiting for the welcome modal to close before initing the main layout, because [Android supports that now](https://github.com/mobify/astro/pull/684)
JIRA: N/A
Linked PRs: 
- https://github.com/mobify/astro/pull/684
- Remove double initialization of welcome modal
- Run app on iOS and Android
- Welcome modal only appears once and can be closed
~~- [ ] CHANGELOG.md has been updated.~~
~~- [ ] Run the generator to make sure it still functions correctly.~~
~~- [ ] Both tab layout and drawer layout are fully functional in ios. (Set `useTabLayout` in `baseConfig`)~~
=> Double Welcome Modal Fix

CHANGELOG.md, android/scaffold/src/main/AndroidManifest.xml, android/scaffold/src/main/java/com/mobify/astro/scaffold/MainActivity.java, android/scaffold/src/main/java/com/mobify/astro/scaffold/plugins/DoubleIconsPlugin.java
JIRA: **https://mobify.atlassian.net/browse/HYB-915**
Linked PRs: **https://github.com/mobify/astro/pull/718** (merged)
- The most recent android refactor requires all `AstroPlugins` to take a couple more parameters and pass them through to their super (`EventRegistrar` and `MessageSender`).
- The refactor also got rid of `CommonApplication` so this must be removed from the `AndroidManifest` otherwise the app will crash
- `npm run deps` and test the Android scaffold
=> Make scaffold work with refactored android

CHANGELOG.md, README.md, android/.idea/gradle.xml, android/.idea/misc.xml, android/.idea/modules.xml, android/scaffold/scaffold.iml, android/settings.gradle, app/app-controllers/welcome-screen/welcomeModalController.js, ios/scaffold.xcworkspace/contents.xcworkspacedata, package.json, scripts/build-dependencies.sh, webpack.app.config.js
Use settings store instead of secure store to store welcome modal state. 
Update to use new astro location in npm
JIRA: None
Linked PRs: 
- Update welcome modal to use settings store
- Change `astro-sdk` to `mobfiy-progressive-app-sdk` in all necessary files
- Run apps in ios and android
- In app.js change `welcomeModalController.show({forced: **false**});` and ensure it is displayed the first time you open it but not the second time. (This doesn't work in the simulator according to some comments in the code)
- Test scaffold on "Cat in the Hat" Android device and ensure it runs.
=> Settings Store Used in Welcome Modal and update to mobify-progressive-app-sdk npm module
